### ISSUE TITLE
Using awsSigv4 in your swagger file

### ISSUE THREAD

**Issue by Nr18** [awslabs/aws-apigateway-swagger-importer#165]
I using awsSigv4 to secure my API calls but it looks like when i import the swagger file with the following settings:

```
securityDefinitions:
    sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"`
```

and in my method 

```
security:
- sigv4: []
```

An export using the AWS Console after importing the API result in:

```
security:
- api_key: []
```

Does the importer support the awsSigv4 method?
