### ISSUE TITLE
Exporting then Importing erases properties on a model

### ISSUE THREAD

**Issue by mclarke47** [awslabs/aws-apigateway-swagger-importer#166]
I defined a model in my Method Response and when I exported my API with swagger + API extensions I got the following model:

```
MyObject:
    type: "object"
    required:
    - "myobject"
    properties:
      myobject:
        type: "object"
        properties:
          field1:
            type: "object"
            properties:
              name:
                type: "string"
          field2:
            type: "string"
          objectField1:
            type: "object"
            properties:
              arr1:
                type: "array"
              arr2:
                type: "array"
              arr3:
                type: "array"
          field3:
            type: "string"
          field4:
            type: "string"
          field5:
            type: "string"
          arr4:
            type: "array"
```

However when I then import this yaml file without making any changes my model definition has changed to:

```
{
   "type":"object",
   "required":[
      "myobject"
   ],
   "properties":{
      "myobject":{
         "type":"object"
      }
   },
   "definitions":{

   }
}
```

A lot of the fields of this model have been lost, is this expected behaviour?
