### ISSUE TITLE
Execution failed due to configuration error: Invalid permissions on Lambda function

### ISSUE THREAD

**Issue by shikasta-kashti** [awslabs/aws-apigateway-swagger-importer#170]
Hi,

I exported a fully working API Gateway stage to JSON file so that I can re-import it using this tool. Everything works fine except that when I try to invoke the API endpoint, I get this error in the logs:

`Tue Feb 16 22:34:16 UTC 2016 : Execution failed due to configuration error: Invalid permissions on Lambda function
Tue Feb 16 22:34:16 UTC 2016 : Method completed with status: 500`

So I went to the Integration Request pane and edited the Lambda Function name, saved it. A window popped up asking to give permissions to API Gateway for invoking the function:

`You are about to give API Gateway permission to invoke your Lambda function:
arn:aws:lambda:us-east-1:*************:function:***************:prod`

 I clicked OK and now it works.

I understand the problem, but how can I make this API Gateway Importer tool to automatically assign the right permissions to API Gateway so that it can invoke those functions?

**Comment by rpgreen** [comment]
We are looking into adding resource-based permissions to the lambda function at import time. In the meantime, current options are:

1) Use the credentials field on the integration to supply a role which API Gateway will assume. This must have an IAM policy to invoke the lambda function and must have a trust relationship for API Gateway to assume the role. See http://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started.html

2) Script the AWS SDK/CLI to add the permission for the API to invoke the lambda function via the Lambda API

I would actually suggest #2 as it should be achievable via the CLI with a few lines of code. You can look at the resource policy created by the console as a guide.

Closing as dupe of https://github.com/awslabs/aws-apigateway-importer/issues/111

**Comment by mim-Armand** [comment]
Same problem here trying to import an API defined in Swagger... :/

**Comment by richarddowner** [comment]
Hi @rpgreen I am also getting this issue when trying to scrip from AWS SDK via powershell. Your suggestion #2 - I'm not sure I understand what you mean, could you explain it in more detail please? Thanks

EDIT:
SOLUTION: Add-LMPermission -FunctionName myfunction -Action lambda:InvokeFunction -Principal apigateway.amazonaws.com -SourceArn arn:aws:execute-api:us-west-2:IAMAccountNumber:_/_/POST/event -StatementId description

**Comment by automagic** [comment]
Just to chime in-  I solved this using the first solution, which worked well for a CloudFormation based swagger import.  Basically I created an execution role, allowing lambda:InvokeFunction to be assumed by apigateway.amazonaws.com.   Then, for each method, I use the credentials property for the x-amazon-gateway-integration swagger extension:

```
    x-amazon-apigateway-integration:
         credentials: !GetAtt GatewayExecutionRole.Arn
         responses:
              ...
```

**Comment by teerakiat** [comment]
here is the command-line which may help anyone who try to solve this problem

##remove lambda permission
aws lambda remove-permission --function-name $lambda_function_name --statement-id "AllowExecutionFromAPIGateway"

## add lambda permission
aws lambda add-permission --function-name $lambda_function_name --statement-id "AllowExecutionFromAPIGateway" --action "lambda:InvokeFunction" --principal "apigateway.amazonaws.com" --source-arn "arn:aws:execute-api:$region:$account_id:$api_rest_id/*/*"

**Comment by AnilRo-Kore** [comment]
Same error, I'm getting. I'm creating the api from Nodejs, via Amazon API Gateway created the API but while do a test it given the error. How can we allow the permission from nodejs.

**Comment by Jun711** [comment]
I got this error when I used AWS Serverless template on Cloud9 to set up my API Gateway. I did what the OP suggested and it worked.

```
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
  - 'AWS::CodeStar'
Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
Resources:
  voices:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: voices.handler
      Runtime: python3.6
      Role:
        'Fn::ImportValue':
          'Fn::Join':
            - '-'
            - - Ref: ProjectId
              - Ref: 'AWS::Region'
              - LambdaTrustRole
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /test/{param}/
            Method: get
```
