### ISSUE TITLE
Update command not overwriting previous request model

### ISSUE THREAD

**Issue by zanona** [awslabs/aws-apigateway-swagger-importer#178]
I have updated my api with the shell command and the ``--update ID` flag but one thing to notice is that if a previous resource method had a model associated with the request, for example, and the updated swagger template has removed it, after updating the API through the importer the model is still declared under 'Method request'.

in example:
#### First update

``` yaml
...
paths:
  /users:
    post:
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/User'
...
```

Result: API has attached User Model to request
#### Second update

``` yaml
...
paths:
  /users:
    post:
      parameters:
        - name: foo
          in: query
          type: string
...
```

Result: Even though the `User` has been removed from the `/users/POST` resource method, it's possible to see that the request still attached to the `User` model under API Gateway console online.
